<?php
function register_my_pattern()
{
    if (function_exists('register_block_pattern')) {
        register_block_pattern(
            'price-box/group/3price box',
            array(
                'title' => 'Regs - Hazem Price Box',
                'description' => '3 ready amazing price boxes',
                'keywords'      => array('price', 'box', 'price box', 'hazem'),
                'content' => '<!-- wp:columns --><div class="wp-block-columns"><!-- wp:column --><div class="wp-block-column"><!-- wp:price-box/group {"addedStyles":{"dottedList":true,"alignList":"left","alignPrice":"center","planNameTag":"h3","planPlacement":"top","borderRadius":21},"theme":"light-theme"} --><div class="wp-block-price-box-group border-21"><div class="price-box-container light-theme"><h3 class="price-box-plan-name">Basic</h3><div class="price-tag-wrapper"><p class="price-tag-initial">$20</p><h1 class="price-tag">$50</h1></div><p class="price-description">For small teams or office</p><ul class="price-box-ul"><li>Great support</li><li>Faster times</li><li>More features</li><li>+ 2 more</li></ul><a href="https://www.google.com"><button class="cta-button">Buy Now</button></a></div></div><!-- /wp:price-box/group --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:price-box/group {"planName":"Pro","addedStyles":{"dottedList":true,"alignList":"left","alignPrice":"center","planNameTag":"h3","planPlacement":"top","borderRadius":18},"theme":"spacy-theme"} --><div class="wp-block-price-box-group border-18"><div class="price-box-container spacy-theme"><h3 class="price-box-plan-name">Pro</h3><div class="price-tag-wrapper"><p class="price-tag-initial">$20</p><h1 class="price-tag">$50</h1></div><p class="price-description">For small teams or office</p><ul class="price-box-ul"><li>Great support</li><li>Faster times</li><li>More features</li><li>+ 2 more</li></ul><a href="https://www.google.com"><button class="cta-button">Buy Now</button></a></div></div><!-- /wp:price-box/group --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:price-box/group {"planName":"Vip++","description":"\u003cmark style=\u0022background-color:rgba(0, 0, 0, 0)\u0022 class=\u0022has-inline-color has-very-light-gray-color\u0022\u003eFor small teams or office\u003c/mark\u003e","featured":true,"style":{"elements":{"link":{"color":{"text":"var:preset|color|very-light-gray"}}}},"textColor":"very-light-gray"} --><div class="wp-block-price-box-group border-0 has-very-light-gray-color has-text-color has-link-color"><div class="price-box-container featured-block"><div class="featured-tag"><p>Featured offer</p></div><h3 class="price-box-plan-name">Vip++</h3><div class="price-tag-wrapper"><p class="price-tag-initial">$20</p><h1 class="price-tag">$50</h1></div><p class="price-description"><mark style="background-color:rgba(0, 0, 0, 0)" class="has-inline-color has-very-light-gray-color">For small teams or office</mark></p><ul class="price-box-ul"><li>Great support</li><li>Faster times</li><li>More features</li><li>+ 2 more</li></ul><a href="https://www.google.com"><button class="cta-button">Buy Now</button></a></div></div><!-- /wp:price-box/group --></div><!-- /wp:column --></div><!-- /wp:columns -->',
            )
        );
    }
}
add_action('init', 'register_my_pattern');
